### ISSUE TITLE
Unable to collect coverage information (Windows)

### ISSUE THREAD

**Issue by larsw** [dtschust/redux-bug-reporter#11]
Hi,

 I'm trying to get the code coverage reporting to work on Windows. First thing I spotted, was that the 
 following syntax is not allowed:
 ` "babel-node $(npm bin)/isparta cover _mocha -- --recursive --require test/setup.js"`

I tried the following instead:

```
> babel-node node_modules/isparta/bin/isparta cover node_modules/mocha/bin/_mocha -- --recursive --require test/setup.js

  Redux Bug Reporter component tests
    Server side render tests
      √ Server side render
    Client side render tests
      √ Happy path (241ms)
      √ customEncode and customDecode properties (230ms)
      √ Custom submit function (210ms)
      √ Error listeners
      √ window.onerror listeners when window.onerror already exists

  Store Enhancer tests
Overriding the store. You should only be doing this if you are using the bug reporter
    √ bug playback functionality
    √ middleware functionality

  8 passing (736ms)

No coverage information was collected, exit without writing coverage information
```

But as the report says, no coverage information was collected. I've also tried to update mocha to 3.0.2. isparta@latest as far as I can tell.

**Comment by dtschust** [comment]
Does this work on Windows?
`"test:cov": "babel-node ./node_modules/.bin/isparta cover _mocha -- --recursive --require test/setup.js"`
I didn't update any versions or anything, so you might want to `rm -rf node_modules && npm install` before trying. I don't have a windows machine to test on so if this works for you I'll merge it in. My result was
```
  Redux Bug Reporter component tests
    Server side render tests
      ✓ Server side render
    Client side render tests
      ✓ Happy path (266ms)
      ✓ customEncode and customDecode properties (232ms)
      ✓ Custom submit function (215ms)
      ✓ Error listeners
      ✓ window.onerror listeners when window.onerror already exists

  Store Enhancer tests
Overriding the store. You should only be doing this if you are using the bug reporter
    ✓ bug playback functionality
    ✓ middleware functionality


  8 passing (2s)

================================================================================
Writing coverage object [/Users/drew/wrk/redux-bug-reporter/coverage/coverage.json]
Writing coverage reports at [/Users/drew/wrk/redux-bug-reporter/coverage]
================================================================================

=============================== Coverage summary ===============================
Statements   : 85.5% ( 230/269 ), 13 ignored
Branches     : 80.6% ( 108/134 ), 9 ignored
Functions    : 87.5% ( 42/48 ), 2 ignored
Lines        : 82.54% ( 156/189 )
================================================================================
```
Thanks!

**Comment by dtschust** [comment]
I'm going to merge in my change assuming it solves your issue, if you're still having problems please feel free to reopen this issue. Thanks!

**Comment by larsw** [comment]
Tried again;
```
> npm run test:cov

> redux-bug-reporter@0.2.0 test:cov C:\code\redux-bug-reporter
> babel-node ./node_modules/.bin/isparta cover _mocha -- --recursive --require test/setup.js

C:\code\redux-bug-reporter\node_modules\.bin\isparta:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\code\redux-bug-reporter\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at C:\code\redux-bug-reporter\node_modules\babel-cli\lib\_babel-node.js:151:24
    at Object.<anonymous> (C:\code\redux-bug-reporter\node_modules\babel-cli\lib\_babel-node.js:152:7)
```

Seems that it picks up the sh script and not the .cmd version of isparta.

After some research, it seems that isparta isn't very Windows friendly, and that the maintainers have left it to rot. Can I recommend that you switch to nyc (an alternative istanbul frontend) instead? It works great on both Windows and unix/linux systems, ex.

`nyc --reporter=text npm test`

**Comment by dtschust** [comment]
@larsw That'd be great if you want to make a PR. Getting code coverage working originally was pretty hairy for me and refactoring it isn't a top priority, since it's not crucial for the developer to have it work. But if you can get it working with `nyc` and verify it in windows I'd love to see it!
